### ISSUE TITLE
feature: API on nostr.today?

### ISSUE THREAD

**Issue by ghost** [darashi/nos.today#8]
Hi, Would it be possible to have an API on nostr.today?

**Comment by darashi** [comment]
What kind of API do you want to have?

nos.today is built on top of NIP-50 https://github.com/nostr-protocol/nips/blob/master/50.md and thus it *is* the API. I have no plans to add APIs other than that to nos.today at this moment. If you want process something automatically, you can issue NIP-50 requests directly to the supporting relays instead of using nos.today.

**Comment by raphaellouisandress** [comment]
Hi @darashi.

> nos.today is built on top of NIP-50 https://github.com/nostr-protocol/nips/blob/master/50.md and thus it is the API. I have no plans to add APIs other than that to nos.today at this moment. If you want process something automatically, you can issue NIP-50 requests directly to the supporting relays instead of using nos.today.

thanks for all information!
